# Generated by Django 5.0.6 on 2024-07-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_loginmodel_password_alter_studentmodel_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
