# Generated by Django 5.0.6 on 2024-07-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_studentmodel_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
