# Generated by Django 5.0.6 on 2024-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
