# Generated by Django 5.0.6 on 2024-07-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_studentmodel_groups_studentmodel_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
